library(mlmRev)
options(show.signif.stars = FALSE)
cntr <- list()
#cntr <- list(EMverbose = TRUE, msVerbose = 1) # uncomment for verbose output
(fm01 <- lmer(langPOST ~ IQ.ver.cen+avg.IQ.ver.cen+(1|schoolNR), bdf, con = cntr))
(fm02 <- lmer(langPOST ~ IQ.ver.cen+avg.IQ.ver.cen+(IQ.ver.cen|schoolNR), bdf, con = cntr))
(fm03 <- lmer(math ~ year+(1|childid)+(1|schoolid), egsingle, con = cntr))
(fm04 <- lmer(math ~ year+(1|childid)+(year|schoolid), egsingle, con = cntr))
(fm05 <- lmer(normexam ~ standLRT + sex + schgend + (1|school), Exam, con = cntr))
(fm06 <- lmer(score ~ gcsecnt + (1|school) + (1|lea), Chem97, con=cntr))
(fm06a <- lmer(score ~ gcsecnt + (1|school) + (1|lea), Chem97, con=c(cntr,list(nit=40))))
(fm07 <- lmer(height ~ age + I(age^2) + I(age^3) + I(age^4) + (age + I(age^2)|Subject),
                 Oxboys, con = cntr))
(fm08 <- lmer(height ~ poly(age,4) + (age + I(age^2)|Subject), Oxboys, con = cntr))
(fm09 <- lmer(attain ~ verbal * sex+(1|primary)+(1|second), ScotsSec, con = cntr))
(fm09a <- lmer(attain ~ verbal * sex+(1|primary)+(1|second), ScotsSec, con = c(cntr,list(nit=40))))
(fm10 <- lmer(attain ~ verbal+sex+(1|primary)+(sex|second), ScotsSec, con = c(cntr,list(nit=40))))
